Repository AritroSaha10/ReliefExchange-ICS4U, pull requests merged in 2023-06, with the labels that each got.

#48 Clean up imports in frontend
  frontend/components/DonationCard.tsx
  frontend/components/Footer.tsx
  frontend/components/Layout.tsx
  frontend/components/Navbar.tsx
  frontend/lib/types/userDataWithDonations.ts
  frontend/pages/_app.tsx
  frontend/pages/donations/[id]/edit.tsx
  frontend/pages/donations/[id]/index.tsx
  frontend/pages/donations/create.tsx
  frontend/pages/donations/index.tsx
  frontend/pages/index.tsx
  frontend/pages/profile.tsx
  frontend/pages/sign-in.tsx
Labels: chore

#56 Add frontend file headers
  frontend/components/DonationCard.tsx
  frontend/components/Dropdown.tsx
  frontend/components/FilterDropdown.tsx
  frontend/components/Footer.tsx
  frontend/components/Layout.tsx
  frontend/components/Navbar.tsx
  frontend/cypress/e2e/protected-routes.cy.ts
  frontend/lib/classNames.ts
  frontend/lib/tag-types.ts
  frontend/pages/_app.tsx
  frontend/pages/donations/[id]/edit.tsx
  frontend/pages/donations/[id]/index.tsx
  frontend/pages/donations/create.tsx
  frontend/pages/donations/index.tsx
  frontend/pages/index.tsx
  frontend/pages/profile.tsx
  frontend/pages/sign-in.tsx
  frontend/pages/sign-out.tsx
Labels: documentation, chore

#57 Added GitHub instructions to README.md
  NAVIGATING_GITHUB.md
  README.md
Labels: documentation, chore

#61 Change tabs to spaces in backend
  backend/endpoints/get/get_donation_from_id.go
  backend/endpoints/get/get_donations.go
  backend/endpoints/get/get_if_admin.go
  backend/endpoints/get/get_if_banned.go
  backend/endpoints/get/get_user_data_from_id.go
  backend/endpoints/post/add_donation.go
  backend/endpoints/post/add_user.go
  backend/endpoints/post/ban_user.go
  backend/endpoints/post/delete_donation.go
  backend/endpoints/post/delete_user.go
  backend/endpoints/post/edit_donation.go
  backend/endpoints/post/report_donation.go
  backend/endpoints/post/validate_captcha_token.go
  backend/firestore.go
  backend/globals/firebase.go
  backend/helpers/add_donation.go
  backend/helpers/add_user.go
  backend/helpers/ban_user.go
  backend/helpers/check_if_admin.go
  backend/helpers/delete_user.go
  backend/helpers/edit_donation.go
  backend/helpers/get_all_donations.go
  backend/helpers/get_donation_from_id.go
  backend/helpers/get_user_data_from_id.go
  backend/helpers/report_donation.go
  backend/main.go
  backend/main_test.go
  backend/mocks/firestore_mock.go
  backend/types/donation.go
  backend/types/user-data.go
Labels: chore

#62 Fix date in header
  backend/endpoints/post/validate_captcha_token.go
Labels: documentation

#67 Run gofmt on backend code
  backend/endpoints/get/get_donation_from_id.go
  backend/endpoints/get/get_donations.go
  backend/endpoints/get/get_if_admin.go
  backend/endpoints/get/get_if_banned.go
  backend/endpoints/get/get_user_data_from_id.go
  backend/endpoints/post/add_user.go
  backend/endpoints/post/ban_user.go
  backend/endpoints/post/delete_donation.go
  backend/endpoints/post/delete_user.go
  backend/endpoints/post/edit_donation.go
  backend/endpoints/post/report_donation.go
  backend/endpoints/post/validate_captcha_token.go
  backend/firestore.go
  backend/globals/firebase.go
  backend/helpers/add_donation.go
  backend/helpers/add_user.go
  backend/helpers/ban_user.go
  backend/helpers/check_if_admin.go
  backend/helpers/delete_user.go
  backend/helpers/edit_donation.go
  backend/helpers/get_all_donations.go
  backend/helpers/get_donation_from_id.go
  backend/helpers/get_user_data_from_id.go
  backend/helpers/report_donation.go
  backend/main.go
  backend/main_test.go
  backend/mocks/firestore_mock.go
  backend/types/donation.go
  backend/types/user-data.go
Labels: chore

#68 Fix translation bug again
  frontend/components/Footer.tsx
Labels: bug
