Repository AritroSaha10/ReliefExchange-ICS4U, pull requests merged in 2023-05, with the labels that each got.

#25 Refactor backend code
  backend/endpoints/get/get_donation_from_id.go
  backend/endpoints/get/get_donations.go
  backend/endpoints/get/get_if_banned.go
  backend/endpoints/get/get_user_data_from_id.go
  backend/endpoints/post/add_donation.go
  backend/endpoints/post/add_user.go
  backend/endpoints/post/ban_user.go
  backend/endpoints/post/delete_donation.go
  backend/endpoints/post/report_donation.go
  backend/endpoints/post/validate_captcha_token.go
  backend/globals/firebase.go
  backend/helpers/add_donation.go
  backend/helpers/add_user.go
  backend/helpers/ban_user.go
  backend/helpers/check_if_admin.go
  backend/helpers/check_if_banned.go
  backend/helpers/get_all_donations.go
  backend/helpers/get_donation_from_id.go
  backend/helpers/get_user_data_from_id.go
  backend/helpers/report_donation.go
  backend/main.go
  backend/main_test.go
Labels: enhancement

#31 Fix submit button issue
  frontend/pages/donations/create.tsx
Labels: bug

#35 Add better documentation to the frontend code
  frontend/components/DonationCard.tsx
  frontend/components/Dropdown.tsx
  frontend/components/FilterDropdown.tsx
  frontend/components/Footer.tsx
  frontend/components/Layout.tsx
  frontend/components/Navbar.tsx
  frontend/lib/firebase/config.ts
  frontend/lib/increasePFPResolution.ts
  frontend/lib/types/userDataWithDonations.ts
  frontend/pages/_app.tsx
  frontend/pages/donations/create.tsx
  frontend/pages/donations/index.tsx
  frontend/pages/index.tsx
  frontend/pages/profile.tsx
  frontend/pages/sign-in.tsx
  frontend/pages/sign-out.tsx
Labels: documentation

#36 Address issues brought up in code walkthrough
  backend/endpoints/post/add_donation.go
  backend/endpoints/post/add_user.go
  backend/endpoints/post/delete_donation.go
  backend/endpoints/post/report_donation.go
  backend/endpoints/post/validate_captcha_token.go
  backend/helpers/add_user.go
  backend/helpers/ban_user.go
  backend/helpers/check_if_admin.go
  backend/helpers/check_if_banned.go
  backend/helpers/get_all_donations.go
  backend/helpers/get_donation_from_id.go
  backend/helpers/get_user_data_from_id.go
  backend/helpers/report_donation.go
  backend/mocks/firestore_mock.go
Labels: documentation

#39 Fix bug where user cannot translate multiple times
  frontend/components/Footer.tsx
Labels: bug

#40 Add icon to website
  frontend/components/Navbar.tsx
  frontend/public/favicon.ico
  frontend/public/logo.png
Labels: enhancement

#42 Add ability to edit donations
  backend/endpoints/get/get_if_admin.go
  backend/endpoints/post/edit_donation.go
  backend/helpers/edit_donation.go
  backend/main.go
  frontend/pages/donations/[id]/edit.tsx
  frontend/pages/donations/[id]/index.tsx
Labels: enhancement
